### ISSUE TITLE
npm run build error 

### ISSUE THREAD

**Issue by nowehity97** [tutaru99/Internet-Radio-Player-Vue#2]
how fix to 
Failed to compile with 2 errors                                                                         17:57:57
 error  in C:/Users/ja/Desktop/Internet-Radio-Player-Vue-main/src/store/index.ts

ERROR in C:/Users/ja/Desktop/Internet-Radio-Player-Vue-main/src/store/index.ts(21,7):
21:7 Element implicitly has an 'any' type because expression of type 'any' can't be used to index type '{}'.
    19 |     },
    20 |     saveLikedStation(state, station) {
  > 21 |       state.likedStations[station.id] = station;
       |       ^
    22 |     },
    23 |     removeLikedStation(state, station) {
    24 |       delete state.likedStations[station.id];

 error  in C:/Users/ja/Desktop/Internet-Radio-Player-Vue-main/src/store/index.ts

ERROR in C:/Users/ja/Desktop/Internet-Radio-Player-Vue-main/src/store/index.ts(24,14):
24:14 Element implicitly has an 'any' type because expression of type 'any' can't be used to index type '{}'.
    22 |     },
    23 |     removeLikedStation(state, station) {
  > 24 |       delete state.likedStations[station.id];
       |              ^
    25 |     }
    26 |   },
    27 |   actions: {},

 ERROR  Build failed with errors.

**Comment by tutaru99** [comment]
Hey nowehity97,
Pull new changes, errors should be fixed now.
Let me know if you encounter any more.

~Cheers.

**Comment by nowehity97** [comment]
> Hey nowehity97, Pull new changes, errors should be fixed now. Let me know if you encounter any more.
> 
> ~Cheers.

**Comment by nowehity97** [comment]
thank you, now it works properly
